# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm globally
RUN npm install -g pnpm

WORKDIR /app

# Copy package files and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the project
RUN pnpm build

# Expose port if needed (Not explicitly mentioned, MCP runs via stdio, so not needed)

CMD ["node", "build/index.js"]
